# Generated by Django 4.0.6 on 2022-07-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_question_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
