# Generated by Django 4.0.6 on 2022-07-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_remove_answer_question_alter_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=213, on_delete=django.db.models.deletion.CASCADE, to='qa.question'),
            preserve_default=False,
        ),
    ]
